#ifndef EG_IR_Projector
#define EG_IR_Projector

#define PROJECTOR_SETTINGS_NUM_BITS 32
#define PROJECTOR_SETTINGS_KHZ 34

#define PROJECTOR_IR_POWER 0xFF15EA

#define PROJECTOR_IR_MUTE 0xFF11EE

// |<<
#define PROJECTOR_IR_SKIP_LEFT 0xFF09F6

// >>|
#define PROJECTOR_IR_SKIP_RIGHT 0xFFC13E

// <<
#define PROJECTOR_IR_FWD 0xFF19E6

// >>
#define PROJECTOR_IR_RWD 0xFF41BE

#define PROJECTOR_IR_PLAY_PAUSE 0xFFC936

#define PROJECTOR_IR_VOL_DOWN 0xFF39C6
#define PROJECTOR_IR_VOL_UP 0xFF31CE

#define PROJECTOR_IR_FLIP 0xFF6B94

#define PROJECTOR_IR_SOURCE 0xFFE916
#define PROJECTOR_IR_ZOOM 0xFF6996
#define PROJECTOR_IR_MENU 0xFF8976
#define PROJECTOR_IR_EXIT 0xFF25DA

#define PROJECTOR_IR_DPAD_UP 0xFFA956
#define PROJECTOR_IR_DPAD_DOWN 0xFF59A6
#define PROJECTOR_IR_DPAD_LEFT 0xFFD926
#define PROJECTOR_IR_DPAD_RIGHT 0xFF9966
#define PROJECTOR_IR_DPAD_OK 0xFF7986

#define PROJECTOR_IR_NUM_1 0xFFE11E
#define PROJECTOR_IR_NUM_2 0xFF619E
#define PROJECTOR_IR_NUM_3 0xFFA15E
#define PROJECTOR_IR_NUM_4 0xFFD12E
#define PROJECTOR_IR_NUM_5 0xFF51AE
#define PROJECTOR_IR_NUM_6 0xFF916E
#define PROJECTOR_IR_NUM_7 0xFFF10E
#define PROJECTOR_IR_NUM_8 0xFF718E
#define PROJECTOR_IR_NUM_9 0xFFB14E
#define PROJECTOR_IR_NUM_0 0xFF49B6

#define PROJECTOR_IR_RECALL 0xFF21DE
#define PROJECTOR_IR_FAV_BACKSPACE 0xFF29D6

#define PROJECTOR_IR_REPEAT_COMMAND 0xFFFFFFFF

#endif